/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.scorpipede.dungeon.infra

import software.amazon.awscdk.core.App

fun main(args: Array<String>) {
    val app = App()
    val id = "DungeonLambdaStack"
    val lambdaStack = DungeonLambdaStack(app, id)
    val stack = DungeonPipelineStack(app, lambdaStack.lambdaCode, id)
    app.synth()
}
